name: Build and Push Docker Image

on:
  push:
    branches:
      - second-R

env:
  IMAGE_NAME: webapp

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} 

      - name: Update deployment image
        run: |
          sed -i "s|image: .*|image: ${{ secrets.ACR_NAME }}.azurecr.io/webapp:${{ github.sha }}|g" deployment.yaml
      - name: Commit manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push